#!/usr/bin/env bash
OS=$(uname)
python=$(which python)
# Check if we are using Anaconda and running on Darwin
[ ${OS} == "Darwin" ] && python=$(which pythonw)
validate=$(which validate.py) || (echo "ossos validate.py is not installed?" && exit 255 )
${python} ${validate} $@
