#! /bin/bash

basedir=`pwd`
syst=`uname -s`
FC="g77 -O"
CC="cc"

case "$syst"
in
SunOS)
    ARCH=SOLARIS
    ;;
Linux)
    ARCH=LINUX
    ;;
Darwin)
    ARCH=DARWIN
    ;;
esac

if [ X"${PREFIX}" == X ]; then
  PREFIX=`pwd`/../..
  export PREFIX
fi

BINDIR=${PREFIX}/bin
BINDIRA=${PREFIX}/bin/$ARCH
LIBDIRA=${PREFIX}/lib/$ARCH
INCLUDEDIR=${PREFIX}/include
CATDIR=${PREFIX}
cd $basedir

#### JJK :-) This isn't perfectly done yet.  Needs to be

./check_perl_version.pl -v v5.6.0 > /dev/null 2>&1
pcheck=$?
if [ ${pcheck} != "0" ]; then
  echo "Need to build a more recent version of PERL"
  exit;
fi
#pcheck=`perl -v | grep 5.8 | wc -l | awk ' { print $1 } '`
#if [ ${pcheck} == "0" ]; then
#  echo "Need to build a more recent version of PERL"
#  exit;
#fi

for file in "*.pl" "*.csh" ; do 
  cp -fv  $file $BINDIR
done;
  cp aclient_linux $BINDIRA/aclient

