#! /bin/bash

source ../config.inc

#### JJK :-) This isn't perfectly done yet.  Needs to be

./check_perl_version.pl -v v5.6.0 > /dev/null 2>&1
pcheck=$?
if [ ${pcheck} != "0" ]; then
  echo "Need to build a more recent version of PERL"
  exit;
fi

for file in "*.pl" "*.csh" ; do 
  cp -fv  $file $BINDIR
done;

cp aclient_$ARCH  $BINDIRA/aclient
cp measure3 ${BINDIR}/measure3

gfortran -o ${BINDIRA}/sky2xypv sky2xypv.f

cd ../Bucket
echo "installing Bucket"
cd nailing
./install.pl --prefix=${PREFIX}
cd ../db
./install.pl --prefix=${PREFIX}
cd ../Table
perl Makefile.PL LIB=$LIBDIR
make 
make install
\rm Makefile
\rm -r blib
\rm -f pm_to_blib

