-- create a table for discoveries in the OSSOS data
--
-- MTB 23 May 2013

CREATE TABLE discoveries(
	discovery_id		VARCHAR(32)			PRIMARY KEY,  -- generated by David's script
	discovery_im1		BIGINT				NOT NULL,     -- 1st image of triplet
	discovery_im2		BIGINT				NOT NULL,     -- 2nd image of triplet
	discovery_im3		BIGINT				NOT NULL,     -- 3rd image of triplet
	a 					DOUBLE PRECISION  	NULL,
	e					DOUBLE PRECISION	NULL,
	i 					DOUBLE PRECISION	NULL,
	q					DOUBLE PRECISION	NULL,
	argP				DOUBLE PRECISION	NULL,
	lonAN				DOUBLE PRECISION	NULL,
	mAnom				DOUBLE PRECISION	NULL,
	H					DOUBLE PRECISION 	NULL,
	mpc_told			BOOLEAN				NOT NULL,
	classification		TEXT				NULL
);

-- so do a join on discovery_ims to get the block, field etc.