#!/bin/bash

source ../config.inc 

. ../MOP_version
cat MOP_version.inc-c | sed "s|AA-MOPVERSION|$MOPversion|" > MOP_version.inc

which `echo ${FC}| cut -d " " -f 1` > /dev/null 2>&1
fcexists=$?
if [ "$fcexists" -eq "0" ]; then
  echo "Creating JMP's library."
  ./make_lib
else
  echo "No Fortran compiler defined. Not building fortran library."
fi

echo "Creating and installing JMP's files."
cc -c -o mycio.o mycio.c

which `echo ${FC}| cut -d " " -f 1` > /dev/null 2>&1
fcexists=$?
echo $fcexists
echo $FFLAGS
echo $LIBDIRA
if [ "$fcexists" -eq "0" ]; then
  $FC -o $BINDIRA/stepZjmp $FFLAGS stepZjmp.f -L$LIBDIRA -ljmp -lcfitsio  -fPIC
  $FC -o $BINDIRA/step0jmp $FFLAGS step0jmp.f -L$LIBDIRA -ljmp -lcfitsio  -fPIC
  $FC -o $BINDIRA/step1jmp $FFLAGS step1jmp.f -L$LIBDIRA -ljmp -lcfitsio  -fPIC
  $FC -o $BINDIRA/step2ajmpl $FFLAGS step2ajmpl.f -L$LIBDIRA -ljmp 
  $FC -o $BINDIRA/step2ajmps step2ajmps.f -L$LIBDIRA -ljmp 
  $FC -o $BINDIRA/step2bjmp step2bjmp.f -L$LIBDIRA -ljmp 
  $FC -o $BINDIRA/step3jmp step3jmp.f -L$LIBDIRA -ljmp 
  $FC -o $BINDIRA/comb-list comb-list.f -L$LIBDIRA -ljmp
  $FC -o $BINDIRA/pipe-eff pipe-eff.f -L$LIBDIRA -ljmp 
  $FC -o $BINDIRA/recover recover.f -L$LIBDIRA -ljmp
  $FC -o $BINDIRA/checktrans checktrans.f -L$LIBDIRA -ljmp
  $FC -o $BINDIRA/global-mag-rate-eff global-mag-rate-eff.f -L$LIBDIRA -ljmp
  $FC -o $BINDIRA/global-area global-area.f -L$LIBDIRA -ljmp
# cat usnoget.f-c | sed "s|AA-CATDIR|$CATDIR|" > usnoget.f
# $FC -o $BINDIRA/usnoget usnoget.f mycio.o 
#  \rm usnoget.f MOP_version.inc
else
  echo "No Fortran compiler defined. Not building fortran programs."
fi

\rm *.o

cp step2jmp $BINDIR/
cp step2ajmp $BINDIR/
cp control_scripts/* $BINDIR/
cp gaiaget.py $BINDIR/

exit
