#! /bin/bash

basedir=`pwd`
syst=`uname -s`
FC="g77 -O2"
CC="cc"

case "$syst"
in
SunOS)
    ARCH=SOLARIS
    ;;
Linux)
    ARCH=LINUX
    ;;
Darwin)
    ARCH=DARWIN
    ;;
esac

if [ X"${PREFIX}" == X ]; then
  PREFIX=`pwd`/../..
  export PREFIX
fi

BINDIR=${PREFIX}/bin
BINDIRA=${PREFIX}/bin/$ARCH
LIBDIRA=${PREFIX}/lib/$ARCH
INCLUDEDIR=${PREFIX}/include
CATDIR=${PREFIX}
cd $basedir

case "$syst"
in
Linux)
    which cf77 > /dev/null 2>&1
    cf77exists=$?
    if [ "$cf77exists" -eq "0" ]; then
	FC="`which cf77` -O6"
    fi
    ;;
esac

$FC -c getpsf.f
$FC -c nstar.f
$FC -c phot.f
$FC -c psf_util.f

ar rv $LIBDIRA/libjmppsf.a getpsf.o nstar.o phot.o psf_util.o
ranlib $LIBDIRA/libjmppsf.a
\rm -f getpsf.o nstar.o phot.o psf_util.o

exit
