#!/bin/bash

source ../config.inc 

echo $FC

$FC  -c caldat.f
$FC  -c check_version.f
$FC  -c close_image.f
$FC  -c convol.f
$FC  -c create_header.f
$FC  -c fit_util.f
$FC  -c get_header.f
$FC  -c match_stars_util.f
$FC  -c match_two_cats.f
$FC  -c momenta.f
$FC  -c open_image.f
$FC  -c read_center.f
$FC  -c read_file_name.f
$FC  -c read_seg.f
$FC  -c readq.f
$FC  -c segment.f
$FC  -c select_stars_util.f
$FC  -c sort.f
$FC  -c thresh.f

ar rv $LIBDIRA/libjmp.a caldat.o check_version.o close_image.o convol.o \
create_header.o fit_util.o get_header.o match_stars_util.o match_two_cats.o \
momenta.o open_image.o read_center.o read_file_name.o read_seg.o readq.o \
segment.o select_stars_util.o sort.o thresh.o
ranlib $LIBDIRA/libjmp.a
\rm -f caldat.o check_version.o close_image.o convol.o \
create_header.o fit_util.o get_header.o match_stars_util.o match_two_cats.o \
momenta.o open_image.o read_center.o read_file_name.o read_seg.o readq.o \
segment.o select_stars_util.o sort.o thresh.o

exit
