#!/bin/sh

if [ ! $# == 3 ]; then
  he="yes"
else
  he="no"
  i=1
  for (( na=$# ; $na > 0 ; na=$((na-1)) )); do
    case "$1" in
    -h|-?)
      he="yes"
      shift
      ;;
    *)
      im[$i]=$1
      i=$((i+1))
      shift
      ;;
    esac
  done
fi

if [ "$he" == "yes" ]; then
  echo "Usage: step2jmp image1 image2 image3"
else
  touch step2jmp.FAILED
  \rm -f step2ajmp.OK step2bjmp.OK step2ajmp.FAILED step2bjmp.FAILED
  step2ajmp ${im[1]} ${im[2]} ${im[3]}
  if [ ! -e step2ajmp.OK ]; then
    exit
  else
    \rm -f step2ajmp.FAILED step2ajmp.OK
  fi
  step2bjmp ${im[1]} ${im[2]} ${im[3]}
  if [ ! -e step2bjmp.OK ]; then
    exit
  else
    \rm -f step2bjmp.FAILED step2bjmp.OK
  fi
  touch step2jmp.OK
fi

exit
