#! /bin/sh

source ../config.inc 


case "$syst"
in
Linux)

# If no Fortran compiler defined, try to install a new one and set it as the
# default.
  echo $syst
  if [ X"${FC}" == X ]; then

# Check the existence of f2c.
    if [ ! -f $BINDIRA/NOF2C ]; then
      which f2c > /dev/null 2>&1
      f2cexists=$?
      if [ "$f2cexists" -eq "1" ]; then
	echo "Installing F2C."
	gunzip < F2C.tar.gz | tar xf -
	cd F2C
	./make-f2c
	cat cf77-c | sed "s|AA-LIBDIR|$LIBDIRA|" | sed "s|AA-BINDIR|$BINDIRA|" | sed "s|AA-INCLUDEDIR|$INCLUDEDIR|" > cf77
	chmod 755 cf77
	cat install-f2c | sed "s|AA-LIBDIR|$LIBDIRA|" | sed "s|AA-BINDIR|$BINDIRA|" | sed "s|AA-INCLUDEDIR|$INCLUDEDIR|" > install-it
	chmod 700 install-it
	./install-it
	\rm install-it
	cd ..
	\rm -rf F2C
	FC="$BINDIRA/cf77 -O6"
      fi
      which cf77 > /dev/null 2>&1
      cf77exists=$?
      if [ "$cf77exists" -eq "0" ]; then
	FC="`which cf77` -O6"
      fi
      cat delete-f2c | sed "s|AA-LIBDIR|$LIBDIRA|g" | sed "s|AA-BINDIR|$BINDIRA|g" | sed "s|AA-INCLUDEDIR|$INCLUDEDIR|g" > delete-it
      chmod 700 delete-it
      $FC -o check-f2c check-f2c.f
      if [ -f check-f2c.o ]; then
	\rm -f check-f2c.o
      fi
      if [ -f check-f2c ]; then
	./check-f2c
	if [ -f keep-f2c ]; then
	  chmod 700 keep-f2c
	  ./keep-f2c
	fi
      fi
      if [ -f delete-it ]; then
	./delete-it
	\rm -f delete-it
	unset FC
      fi
    fi
  fi
  ;;
esac

# Check we got a Fortran compiler.
if [ X"${FC}" == X ]; then
  echo "No fortran comppiler defined. Please define one, or parts of the"
  echo "install will not work. Name of Fortran comppiler: "
  read ans
  FC=${ans}
  export FC
fi

# Check the existence of the cfitsio library.

if [ ! -f $LIBDIRA/libcfitsio.a ]; then
    echo "Installing cfitsio library."
#    mkdir cfitsio
#    cd cfitsio
#    gunzip < ../cfitsio142.tar.gz | tar xf -
    gunzip < cfitsio2470.tar.gz | tar xf -
    cd cfitsio
    ./configure -libdir=$LIBDIRA --bindir=$BINDIRA --include=$INCLUDEDIR
    make
    make install
    make imcopy fitscopy listhead
    strip imcopy fitscopy listhead
    cp imcopy fitscopy listhead $BINDIRA/
    cp lib/libcfitsio.a $LIBDIRA/
    cp include/fitsio*.h $INCLUDEDIR/
    cp include/longnam.h $INCLUDEDIR/
    cd ..
    \rm -rf cfitsio
fi
