#! /bin/bash

source ../config.inc 

syst=`uname -s`

BASEDIR=`pwd`
MATCHDIR=$BASEDIR/match
PERLDIR=`which perl`
. ../MOP_version

MAKEWCSARGS=" "

case "$syst"
in
SunOS)
    ARCH=SOLARIS
    MAKEWCSARGS="-f Makefile.solaris"
    SEXARCH=solaris
    ;;
Linux)
    ARCH=LINUX
    MAKEWCSARGS=" "
    SEXARCH=linuxpc
    ;;
esac

BINDIRA=${PREFIX}/bin/${ARCH}
BINDIR=${PREFIX}/bin
CONFIGDIR=${PREFIX}/config

echo ${BINDIRA}

# Creating executable files

echo "Making Matt's files."
make clean
make all

basedir=`pwd`

# Install sextractor
# Now use the system install sex
which sex >& /dev/null || echo "Please install sextractor on your system."

# Install match

cd ${basedir}
if [ ! -f $BINDIRA/match ]; then
    echo "Installing match."
    gunzip < match-tar.gz | tar xf -
    cd match
    make clean
    make all
    cp match $BINDIRA/
    cd ..
    \rm -rf match
fi

# Install wcstools
which gethead >& /dev/null || echo "Please ensure that gethead, part of the WCSTools package, is in your path."

## Editing configuration files
## but use these sex configs still

echo "Editing configuration files."
cd ${basedir}/config
cat fnd-c.sex | sed "s|AA-CONFIGDIR|$CONFIGDIR|" > fnd.sex.edited
\mv fnd.sex.edited ${CONFIGDIR}/fnd.sex
cat fnd_bright-c.sex | sed "s|AA-CONFIGDIR|$CONFIGDIR|" > fnd_bright.sex.edited
\mv fnd_bright.sex.edited ${CONFIGDIR}/fnd_bright.sex
\cp * ${CONFIGDIR}/
cd ${basedir}

cat match_matt-c | sed "s|AA-PERLDIR|$PERLDIR|" > match_matt.edited
\mv match_matt.edited match_matt
cat step1matt-c | sed "s|AA-PERLDIR|$PERLDIR|" | sed "s|AA-CONFIGDIR|$CONFIGDIR|" | sed "s|AA-MOPversion|$MOPversion|" > step1matt.edited
\mv step1matt.edited step1matt
cat step2matt_jmp-c | sed "s|AA-PERLDIR|$PERLDIR|" | sed "s|AA-MOPversion|$MOPversion|" > step2matt_jmp.edited
\mv step2matt_jmp.edited step2matt_jmp
cat step3matt-c | sed "s|AA-PERLDIR|$PERLDIR|" | sed "s|AA-MOPversion|$MOPversion|" > step3matt.edited
\mv step3matt.edited step3matt
cat step3jjk-c.pl | sed "s|AA-PERLDIR|$PERLDIR|" | sed "s|AA-MOPversion|$MOPversion|" > step3jjk.edited
\mv step3jjk.edited step3jjk

# Install files compiled from c source code in the right place.

echo "Installing Matt's files."
\mv add_mag $BINDIRA/
\mv add_mag_fwhm $BINDIRA/
\mv bright $BINDIRA/
\mv convert_mjd $BINDIRA/
\mv cr_elim $BINDIRA/
\mv cr_elim_fwhm $BINDIRA/
\mv fwhm_medav $BINDIRA
\mv gettime-exp $BINDIRA
\mv kbo_gen $BINDIRA
\mv non_stationary $BINDIRA
\mv satur $BINDIRA
\mv search $BINDIRA
\mv select_trans_stars $BINDIRA
\mv select_trans_stars_fwhm $BINDIRA
\mv trans $BINDIRA

# Install perl files in the right place.

chmod 755 match_matt step1matt step3matt step2matt_jmp step3jjk
\mv match_matt $BINDIR
\mv step1matt $BINDIR
\mv step2matt_jmp $BINDIR
\mv step3matt $BINDIR
\mv step3jjk $BINDIR

exit
