#! /bin/bash

source ../config.inc

#FC=g77
#FC=ifort
#export FC

echo "Creating starlist library."
echo "cio compile..."
# the $ARCH is defined to modify the names of 
# routines in cio to have only one trailing _
cc -O -D$ARCH  -c -o cio.o cio.c

which `echo ${FC}| cut -d " " -f 1` > /dev/null 2>&1
fcexists=$?
if [ "$fcexists" -eq "0" ]; then
  $FC  -c -o corner.o corner.f
  $FC  -c -o eatit.o eatit.f
  $FC  -c -o saveit.o saveit.f
  $FC  -c -o square.o square.f
  $FC  -c -o readq.o readq.f
  cat whereis.f-c | sed "s|AA-CATDIR|$CATDIR|" > whereis.f
  $FC  -c -o whereis.o whereis.f
  ar vr $LIBDIRA/libstarlist.a cio.o corner.o eatit.o saveit.o square.o readq.o whereis.o 
  ranlib $LIBDIRA/libstarlist.a
  ranlib $LIBDIRA/libstarlist.a
  \rm whereis.f

  echo "Creating and installing Hans' files."
  $FC -o $BINDIRA/mkpltsol mkpltsol.f -L$LIBDIRA -lstarlist
  $FC -o $BINDIRA/measure3 measure3.f
  $FC -o $BINDIRA/measure-manual measure-manual.f
  $FC -o $BINDIRA/hansastone hansastone.f
  $FC -o $BINDIRA/hansastmany hansastmany.f
else
  echo "No Fortran compiler defined. Not building fortran programs."
fi

\rm *.o

if [ ! -f $USNODIR/catalog.toc ]; then
    cat catalog.toc-c | sed "s|AA-USNODIR|$USNODIR|" > ${PREFIX}/catalog.toc
fi

echo "Create a link $USNODIR pointing to the directory containing the USNO catalog."

exit
