#! /bin/sh

source config.inc 

initdir=$basedir

echo "Install in utils area (y|n)?"
read ans

if [ $ans == "y" ]; then 
  echo "Installing utils."
  cd utils
  . ./install_utils
  cd $initdir
fi

echo "Install in Hans' pipeline area (y|n)?"
read ans

if [ $ans == "y" ]; then 
  echo "Installing Hans' pipeline."
  cd hans
  ./install_pipehans
  cd $initdir
fi

echo "Install in J-M' pipeline area (y|n)?"
read ans

if [ $ans == "y" ]; then 
  cd jmp
  echo "Installing JMP's pipeline."
  ./install_pipejmp
  cd $initdir
fi

echo "Install in Matt' pipeline area (y|n)?"
read ans

if [ $ans == "y" ]; then 
  echo "Installing Matt's pipeline."
  cd pipematt
  ./install_pipematt
  cd $initdir
fi

echo "Install in jjk pipeline area (y|n)?"
read ans

if [ $ans == "y" ]; then 
  cd jjk
  echo "Installing JJ's pipeline."
  ./install_jjk
  cd $initdir
fi

echo "Install in lstools pipeline area (y|n)?"
read ans

if [ $ans == "y" ]; then 
  cd lstools
  echo "Installing lstools' pipeline."
  ./install_lstools
  cd $initdir
fi

./make_links

echo "Add $BINDIRA and $BINDIR (in that order) to your path."
echo "Add $LIBDIRA to the LD_LIBRARY_PATH environment variable."
echo "Add $LIBDIR to the PERLLIB environment variable"

exit
