#! /bin/sh

source config.inc

#basedir=`pwd`
#if [ "X${PREFIX}" == "X" ]; then
#  PREFIX=${basedir}
#fi

cd $PREFIX
if [ -f MOP-SOURCE-DIR ]; then
    cd ..
fi
PREFIX=`pwd`
export PREFIX
cd $basedir


if [ -x $USNODIR ]; then 
   echo "$USNODIR already exists, skipping link step"
   ls -l $USNODIR
else
   echo "Directory of USNO catalog files: "
   read usnoloc
   echo "Linking $usnoloc to $USNODIR "
   ln -s $usnoloc $USNODIR
fi

echo "IRAF home directory: [$HOME/iraf] "
read irafhome
if [ X"$irafhome" = X ]; then
  irafhome=$HOME/iraf
fi
\rm $irafhome/kinky
ln -s $basedir/kinky $irafhome/kinky

exit
